FROM python:3.11.2

RUN apt update && apt install -y vim
RUN apt install -y libhdf5-serial-dev

# install requirements that are needed for development
COPY requirements.txt .
RUN pip install -r requirements.txt