flavour_categories:
  bjets:
    colour: "#1f77b4"  # blue
    legend_label: $b$-jets
  cjets:
    colour: "#ff7f0e"  # orange
    legend_label: $c$-jets
  ujets:
    colour: "#2ca02c"  # green
    legend_label: light-flavour jets
  taujets:
    colour: "#7c5295"  # purple
    legend_label: $\tau$-jets
  singlebjets:
    colour: "#1f77b4"  # blue (same as bjets)
    legend_label: $b$-jets
  bbjets:
    colour: "#012F51"  # dark blue
    legend_label: $bb$-jets
  singlecjets:
    colour: "#ff7f0e"  # orange (same as cjets)
    legend_label: $c$-jets
  ccjets:
    colour: ""
    legend_label: $cc$-jets

# plot style definitions
hist_err_style:
  fill: False
  linewidth: 0
  hatch: "/////"
  edgecolor: "#666666"