name: Docs
concurrency:
  group: ${{ github.workflow }}-${{ startsWith(github.ref, 'refs/tags/') && github.sha || (github.event.pull_request.number || github.ref) }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Cache docs environment
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        uses: actions/cache@v4
        with:
          path: ~/.cache/docs
          key: mkdocs-material-${{ env.cache_id }}
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: uv sync --extra dev && uv pip install -r docs/requirements.txt

      - name: Build Docs
        run: mkdocs build

      - name: Deploy Docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
